apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: yehezkel1086/todo-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              value: "todo_app"
            - name: APP_ENV
              value: "development"
            - name: HTTP_HOST
              value: "127.0.0.1"
            - name: HTTP_PORT
              value: "8080"
